#!/bin/bash

function help() {
    echo "Available subcommands:"
    echo "  apt"
    echo "  nvidia"
    echo "  sysinfo"
    echo "  clean"
    echo "Run 'nexa <subcommand> help' to see the help for a specific subcommand."
}

if [[ -z "$1" ]]; then
    help
    exit 1
fi

case "$1" in
    apt)
        shift
        /usr/local/bin/nexa-apt/nexa-apt "$@"
        ;;
    nvidia)
        shift
        /usr/local/bin/nexa-nvidia/nexa-nvidia "$@"
        ;;
    sysinfo)
        shift
        /usr/local/bin/nexa-sysinfo/nexa-sysinfo "$@"
        ;;
    clean)
        shift
        /usr/local/bin/nexa-clean/nexa-clean "$@"
        ;;        
    *)
        help
        exit 1
        ;;
esac
